<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.1">
    <PropertyGroup>
        <Authors>Pistachio Herald</Authors>
        <Version>0.0.0.1</Version>
        <RootNamespace>MinigameCollection</RootNamespace>
        <AssemblyName>MinigameCollection</AssemblyName>
        <FileVersion>0.0.0.1</FileVersion>
        <AssemblyVersion>0.0.0.1</AssemblyVersion>
        <Description>A collection of chat minigames for FFXIV</Description>
        <PackageProjectUrl>https://https://github.com/Pistachio-dev/MinigameCollection</PackageProjectUrl>
        <PackageId>MinigameCollection</PackageId>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj" />
        <ProjectReference Include="..\Common\CommonServices.csproj" />
        <ProjectReference Include="..\DalamudBasics\DalamudBasics\DalamudBasics.csproj" />
        <ProjectReference Include="..\PersistentModel\PersistentModel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="DalamudPackager" Version="14.0.1" />
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="1.2.39" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Games\NoGame\" />
    </ItemGroup>
</Project>
