// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistentModel;

#nullable disable

namespace PersistentModel.Migrations
{
    [DbContext(typeof(MinigameCollectionDbContext))]
    [Migration("20260125132323_Latest changes")]
    partial class Latestchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransactionEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cause")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HostPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InUseDiff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealGil")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PatronPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("PlayerCashRecordEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredDiff")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostPlayerId");

                    b.HasIndex("PatronPlayerId");

                    b.HasIndex("PlayerCashRecordEntityId");

                    b.ToTable("GilTransactions");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecordEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InUseFake")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InUseReal")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerOOGDataId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredFake")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredReal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOOGDataId")
                        .IsUnique();

                    b.ToTable("PlayerCashRecords");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifierEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIdentityChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("PlayerOOGDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlayerOOGDataId");

                    b.ToTable("PlayerIdentifiers");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransactionEntity", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", "PatronPlayer")
                        .WithMany()
                        .HasForeignKey("PatronPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersistentModel.Model.Banking.PlayerCashRecordEntity", null)
                        .WithMany("History")
                        .HasForeignKey("PlayerCashRecordEntityId");

                    b.Navigation("HostPlayer");

                    b.Navigation("PatronPlayer");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecordEntity", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", "PlayerOOGData")
                        .WithOne("CashRecord")
                        .HasForeignKey("PersistentModel.Model.Banking.PlayerCashRecordEntity", "PlayerOOGDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifierEntity", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", "PlayerOOGData")
                        .WithMany("PreviousIdentities")
                        .HasForeignKey("PlayerOOGDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecordEntity", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGDataEntity", b =>
                {
                    b.Navigation("CashRecord")
                        .IsRequired();

                    b.Navigation("PreviousIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
