// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistentModel;

#nullable disable

namespace PersistentModel.Migrations
{
    [DbContext(typeof(MinigameCollectionDbContext))]
    partial class MinigameCollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransaction", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HostPlayerId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHouseCut")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealGil")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerCashRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HostPlayerId1");

                    b.HasIndex("PlayerCashRecordId");

                    b.ToTable("GilTransactions");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecord", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InUseFake")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InUseReal")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlayerOOGDataID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredFake")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredReal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOOGDataID")
                        .IsUnique();

                    b.ToTable("PlayerCashRecords");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifier", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMetUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("PlayerOOGDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlayerOOGDataId");

                    b.ToTable("PlayerIdentifiers");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransaction", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersistentModel.Model.Banking.PlayerCashRecord", "PlayerCashRecord")
                        .WithMany("History")
                        .HasForeignKey("PlayerCashRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostPlayer");

                    b.Navigation("PlayerCashRecord");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecord", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", "PlayerOOGData")
                        .WithOne("CashRecord")
                        .HasForeignKey("PersistentModel.Model.Banking.PlayerCashRecord", "PlayerOOGDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifier", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", "PlayerOOGData")
                        .WithMany("PreviousIdentities")
                        .HasForeignKey("PlayerOOGDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerOOGData");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecord", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGData", b =>
                {
                    b.Navigation("CashRecord")
                        .IsRequired();

                    b.Navigation("PreviousIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
