// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistentModel;

#nullable disable

namespace PersistentModel.Migrations
{
    [DbContext(typeof(MinigameCollectionDbContext))]
    partial class MinigameCollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHouseCut")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealGil")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatronPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerCashRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostPlayerId");

                    b.HasIndex("PatronPlayerId");

                    b.HasIndex("PlayerCashRecordId");

                    b.ToTable("GilTransactions");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FakeGilBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RealGilBalance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerCashRecords");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMetUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerOOGDataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlayerOOGDataId");

                    b.ToTable("PlayerIdentifiers");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashRecordId");

                    b.HasIndex("Name");

                    b.ToTable("PlayerOOGEntries");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.GilTransaction", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", "PatronPlayer")
                        .WithMany()
                        .HasForeignKey("PatronPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersistentModel.Model.Banking.PlayerCashRecord", null)
                        .WithMany("History")
                        .HasForeignKey("PlayerCashRecordId");

                    b.Navigation("HostPlayer");

                    b.Navigation("PatronPlayer");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerIdentifier", b =>
                {
                    b.HasOne("PersistentModel.Model.PlayerManagement.PlayerOOGData", null)
                        .WithMany("PreviousIdentities")
                        .HasForeignKey("PlayerOOGDataId");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGData", b =>
                {
                    b.HasOne("PersistentModel.Model.Banking.PlayerCashRecord", "CashRecord")
                        .WithMany()
                        .HasForeignKey("CashRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRecord");
                });

            modelBuilder.Entity("PersistentModel.Model.Banking.PlayerCashRecord", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("PersistentModel.Model.PlayerManagement.PlayerOOGData", b =>
                {
                    b.Navigation("PreviousIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
